### ISSUE TITLE
ExoPlayer not playing MIDI files

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#152]
I was able to play MIDI files fine when I was using the regular Android implementation. However, since switching to the ExoPlayer implementation, they do not play. I get the following in the debug log:

```
03-07 21:56:02.549 E/ExoPlayerImplInternal(27305): Source error.
03-07 21:56:02.549 E/ExoPlayerImplInternal(27305): com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
03-07 21:56:02.549 E/ExoPlayerImplInternal(27305): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:678)
03-07 21:56:02.549 E/ExoPlayerImplInternal(27305): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:602)
03-07 21:56:02.549 E/ExoPlayerImplInternal(27305): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
03-07 21:56:02.549 E/ExoPlayerImplInternal(27305): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
03-07 21:56:02.549 E/ExoPlayerImplInternal(27305): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-07 21:56:02.549 E/ExoPlayerImplInternal(27305): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-07 21:56:02.549 E/ExoPlayerImplInternal(27305): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-07 21:56:02.549 E/ExoPlayerImplInternal(27305): 	at java.lang.Thread.run(Thread.java:818)
```

Is this a limitation of ExoPlayer, or is there something we can do to get it working?

**Comment by SimonSimCity** [comment]
I wonder if this isn't something for https://github.com/google/ExoPlayer ... See https://google.github.io/ExoPlayer/supported-formats.html

**Comment by martijn00** [comment]
Related to https://github.com/google/ExoPlayer/issues/4592. Will close this untill Exoplayer supports it.
