### ISSUE TITLE
Stream problem Android - No content provider

### ISSUE THREAD

**Issue by rudacs** [martijn00/XamarinMediaManager#368]
### Reproduction steps

```
var media = new MediaFile("http://assembleia.org.br:8028/;stream.mp3", MediaFileType.Audio, ResourceAvailability.Remote);
await CrossMediaManager.Current.Play(media);
```

### Log

```
[MediaPlayer] Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: http://assembleia.org.br:8028/;stream.mp3
[MediaPlayer] setDataSource IOException | SecurityException happend : 
[MediaPlayer] java.io.FileNotFoundException: No content provider: http://assembleia.org.br:8028/;stream.mp3
[MediaPlayer] 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1141)
[MediaPlayer] 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:991)
[MediaPlayer] 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:914)
[MediaPlayer] 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1121)
```

### Expected outcome
Play the song.

### Actually happening
No sound is played.

### Your setup

Which version of MediaManager are you using: 0.4.5
Which platform iOS, Droid, UWP, Xamarin.Forms: Xamarin.Forms, problem only Android

**Comment by coolhunter33** [comment]
I am experiencing the same problem.
@rudacs , have you resolved this?
