### ISSUE TITLE
OnElementChanged Object reference not set exception

### ISSUE THREAD

**Issue by bunkerbilly** [martijn00/XamarinMediaManager#372]
Xamarin Forms UWP

The video plays fine it is only until i call Navigation.PopModalAsync() that i then get this error.

it works fine on IOS where i am not doing anything different.

 Plugin.MediaManager.Forms.UWP.VideoViewRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.Dispose(Boolean disposing)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.Dispose()
   at Xamarin.Forms.Platform.UWP.VisualElementExtensions.Cleanup(VisualElement self)
   at Xamarin.Forms.Platform.UWP.Platform.<SetCurrent>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

**Comment by cartmax** [comment]
I have the same issue, do you know when you can solve this problem?
