### ISSUE TITLE
[Bug] [WPF] InvalidOperationException thrown when playing a video

### ISSUE THREAD

**Issue by Nessitro** [martijn00/XamarinMediaManager#585]
## 🐛 Bug Report

playing a video throws an InvalidOperationException

### Expected behavior
Video playing without crash
### Reproduction steps
1. add MediaManager forms nuget to the solution
2. call MediaManager.CrossMediaManager.Current.Init(); Forms.Init(); ... in MainWindow.xaml.cs
3. add videoView xaml with Source and AutoPlay=True or from code
4. app throws:

*Unable to return a TimeSpan property value for a Duration value of 'Automatic'. Check the HasTimeSpan property before requesting the TimeSpan property value from a Duration.*

#### **InvalidOperationException** Source: PresentationCore

at System.Windows.Duration.get_TimeSpan()
   at MediaManager.MediaManagerImplementation.get_Duration()
   at MediaManager.Forms.VideoView.MediaManager_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at MediaManager.NotifyPropertyChangedBase.OnPropertyChanged(String propertyName)
   at MediaManager.MediaManagerBase.OnStateChanged(Object sender, StateChangedEventArgs e)
   at MediaManager.MediaManagerBase.set_State(MediaPlayerState value)
   at MediaManager.Platforms.Wpf.Player.WpfMediaPlayer.<Play>d__27.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediaManager.MediaManagerBase.<PlayAsCurrent>d__79.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediaManager.MediaManagerBase.<Play>d__71.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Portable.ViewModels.Home.HomeViewViewModel.<OnAppearing>d__39.MoveNext() in C:\App\Solution\Portable\ViewModels\Home\HomeViewModel.cs:line 69

### Configuration
* Visual Studio 2019 **16.2.1**
* Xamarin.Forms **4.1.0.673156**
* Xamarin.Forms.Platform.WPF **4.1.0.673156**
* Plugin.MediaManager.Forms **0.8.6**

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Nessitro** [comment]
@martijn00 I used older versions of the package, same problem occurs

**Comment by martijn00** [comment]
@Nessitro can you check 0.8.8?

**Comment by Nessitro** [comment]
I tried 0.8.8. The previous exception **is gone** but the video **doesn't render on screen**. I can **hear the audio playing in background tho**

current config:
* Visual Studio 2019 **16.2.4**
* Xamarin.Forms **4.2.0.709249**
* Xamarin.Forms.Platform.WPF **4.2.0.709249**
* Plugin.MediaManager.Forms **0.8.8**
