### ISSUE TITLE
Xamarin.Forms - Streaming from Encrypted Azure Media Services works on iOS and fails under Android

### ISSUE THREAD

**Issue by richp582** [martijn00/XamarinMediaManager#608]
## 🐛 Bug Report

I have media (music) stored in an Azure Streaming Media Endpoint.  The music is protected by token based authentication and as such during start-up I add the Auth Header like below:

`CrossMediaManager.Current.RequestHeaders.Add("Authorization", $"Bearer {token}");`

Then when I'm ready to play a song I do the following:

```
var url = song.DirectUrls.First(s => s.Contains("m3u")); //aapl
var mediaitem = await CrossMediaManager.Current.Extractor.CreateMediaItem(url);
mediaitem.MediaType = MediaType.Hls;

var item = await CrossMediaManager.Current.Play(mediaitem);
```

This works perfect in XF iOS and Fails in XF Android.

Here is the error message I see for XF Android:

```
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[MediaHTTPConnection] response code = 200
[MediaHTTPConnection] mTotalSize is -1
setDataSource failed: status = 0x80000000
[Choreographer] Skipped 151 frames!  The application may be doing too much work on its main thread.
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[AudioManager] requestAudioFocus status : 1
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[art] Waiting for a blocking GC Alloc
[art] Clamp target GC heap from 142MB to 128MB
[art] WaitForGcToComplete blocked for 28.848ms for cause Alloc
[art] Starting a blocking GC Alloc
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[System.out] (HTTPLog)-Static: isSBSettingEnabled false
[ExoPlayerImplInternal] Source error.
[ExoPlayerImplInternal] com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 401
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.source.chunk.DataChunk.load(DataChunk.java:75)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
[ExoPlayerImplInternal] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
[ExoPlayerImplInternal] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
[ExoPlayerImplInternal] 	at java.lang.Thread.run(Thread.java:762)

```

It appears that it cannot access the media as seen by the ExoPlayer returning a 401 however the log does indicate: `[MediaHTTPConnection] response code = 200` so I'm not sure.

I've also tried switching the url to use the mpd format and set the MediaType to Dash but it still fails, although in this case ExoPlayer complains with 
```
[ExoPlayerImplInternal] Source error.
[ExoPlayerImplInternal] java.io.EOFException
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:265)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:102)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:110)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:427)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:315)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:89)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
[ExoPlayerImplInternal] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
[ExoPlayerImplInternal] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
[ExoPlayerImplInternal] 	at java.lang.Thread.run(Thread.java:762)

```

### Expected behavior

Should be able to stream on both XF iOS and XF Android

### Configuration

**Version:** 0.8.8

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by richp582** [comment]
I rolled back to 0.8.5 and am experiencing the same results.

**Comment by richp582** [comment]
I can put together a sample if you like, but in terms of content to test this on you can grab the video url and token from the `AES (JWT token) - On Demand [Tears of Steel Teaser]` demo @ http://ampdemo.azureedge.net/.

Encrypted Video URL: `https://amssamples.streaming.mediaservices.windows.net/830584f8-f0c8-4e41-968b-6538b9380aa5/TearsOfSteelTeaser.ism/manifest(format=m3u8-aapl)`
Auth Header: `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiI5ZGRhMGJjYy01NmZiLTQxNDMtOWQzMi0zYWI5Y2M2ZWE4MGIiLCJpc3MiOiJodHRwOi8vdGVzdGFjcy5jb20vIiwiYXVkIjoidXJuOnRlc3QiLCJleHAiOjE3MTA4MDczODl9.lJXm5hmkp5ArRIAHqVJGefW2bcTzd91iZphoKDwa6w8`

Hope that helps,
Thanks!

**Comment by richp582** [comment]
I started taking a look and trying to debug the code, but nothing was jumping out at me... I appreciate the effort you put into these open source projects, if you've got any hints or guesses on what might be wrong, I'd be more than happy to try and fix it and PR if I am successful.

Thanks,
Rich

**Comment by martijn00** [comment]
@richp582 The headers are updated here: https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/Player/AndroidMediaPlayer.cs#L257

The actual media source for HLS is created here: https://github.com/martijn00/XamarinMediaManager/blob/64e3191082c6fcdc831c785a718d9810dcada21b/MediaManager/Platforms/Android/Media/MediaItemExtensions.cs#L50

Maybe you can try debug those areas to see where it fails?

**Comment by richp582** [comment]
So using the URL and token above...

and replacing the MediaManager.RequestHeaders with a new Dictionary Instance

I got a different error:

```
10-04 11:28:25.417 E/ExoPlayerImplInternal(12945): Source error.
10-04 11:28:25.417 E/ExoPlayerImplInternal(12945): com.google.android.exoplayer2.source.hls.SampleQueueMappingException: Unable to bind a sample queue to TrackGroup with mime type audio/mp4a-latm.
10-04 11:28:25.417 E/ExoPlayerImplInternal(12945): 	at com.google.android.exoplayer2.source.hls.HlsSampleStream.maybeThrowError(HlsSampleStream.java:64)
10-04 11:28:25.417 E/ExoPlayerImplInternal(12945): 	at com.google.android.exoplayer2.BaseRenderer.maybeThrowStreamError(BaseRenderer.java:129)
10-04 11:28:25.417 E/ExoPlayerImplInternal(12945): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:538)
10-04 11:28:25.417 E/ExoPlayerImplInternal(12945): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
10-04 11:28:25.417 E/ExoPlayerImplInternal(12945): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-04 11:28:25.417 E/ExoPlayerImplInternal(12945): 	at android.os.Looper.loop(Looper.java:193)
10-04 11:28:25.417 E/ExoPlayerImplInternal(12945): 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

If I switched the URL to `(format=mpd-time-csf) and set the mediaType to Dash, I get this

```
10-04 11:31:46.104 E/ExoPlayerImplInternal(13285): Source error.
10-04 11:31:46.104 E/ExoPlayerImplInternal(13285): com.google.android.exoplayer2.ParserException: Skipping atom with length > 2147483647 (unsupported).
10-04 11:31:46.104 E/ExoPlayerImplInternal(13285): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:412)
10-04 11:31:46.104 E/ExoPlayerImplInternal(13285): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:310)
10-04 11:31:46.104 E/ExoPlayerImplInternal(13285): 	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:89)
10-04 11:31:46.104 E/ExoPlayerImplInternal(13285): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
10-04 11:31:46.104 E/ExoPlayerImplInternal(13285): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-04 11:31:46.104 E/ExoPlayerImplInternal(13285): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-04 11:31:46.104 E/ExoPlayerImplInternal(13285): 	at java.lang.Thread.run(Thread.java:764)
```

Going to keep digging but figured I'd mention it since they're definitely different error messages now!

Thanks for  the quick reply.

**Comment by awatertrevi** [comment]
@richp582 I ran into the same issue a couple of weeks ago. 

We simply wrote our own implementation using the ExoPlayer bindings.

https://github.com/brminnick/AzureMediaServicesSampleApp/issues/6

**Comment by JohnGalt1717** [comment]
Any idea when this is going to be properly fixed? The standard non-exoplayer works fine with headers.

**Comment by richp582** [comment]
Unfortunately, we ended up going with a home grown solution and are no
longer using this package.  I check in every week or two to see if it get's
fixed, I'd love to come back!

**Comment by martijn00** [comment]
@richp582 @JohnGalt1717 @awatertrevi maybe it is a better idea to pay me to fix this instead of making homebrew ;)

**Comment by JohnGalt1717** [comment]
@martijn00 How much to get this working with RequestHeaders done in an iOS compliant way that isn't using a hidden API that they're now rejecting, and android, and UWP and all with caption files at different URLs?

I.e. we have a playlist file from Azure Media Services, and then separate WebVTT captions. The playlist file is protected behind a bearer token. We need to be able to do the request from Azure Media Services AND get WebVTT captions working from separate files. This is straightforward on Android with VideoPlayer (and doesn't work with the current bindings of exoplayer) and presumably works with AVAssetResourceLoaderDelegate on iOS. UWP is trivial.

But I'd like it all working with Fullscreen on all 3 platforms:

1. Headers 
2. External WebVTT captions with caption selection
3. Full Screen of said video
4. Write it in such a way that you or others can easily add Fairplay, WideVine, and PlayReady later as we may need it.

We'd contribute it back to the community.

**Comment by ps-rpopola** [comment]
> @martijn00 How much to get this working with RequestHeaders done in an iOS compliant way that isn't using a hidden API that they're now rejecting, and android, and UWP and all with caption files at different URLs?
> 
> I.e. we have a playlist file from Azure Media Services, and then separate WebVTT captions. The playlist file is protected behind a bearer token. We need to be able to do the request from Azure Media Services AND get WebVTT captions working from separate files. This is straightforward on Android with VideoPlayer (and doesn't work with the current bindings of exoplayer) and presumably works with AVAssetResourceLoaderDelegate on iOS. UWP is trivial.
> 
> But I'd like it all working with Fullscreen on all 3 platforms:
> 
> 1. Headers
> 2. External WebVTT captions with caption selection
> 3. Full Screen of said video
> 4. Write it in such a way that you or others can easily add Fairplay, WideVine, and PlayReady later as we may need it.
> 
> We'd contribute it back to the community.

When did you get a rejection?  I've got an implementation that uses the hidden api, and just published a build to the store like a week ago.

**Comment by JohnGalt1717** [comment]
We haven't yet, but it's coming, and in any event, you have a choice: Captions, or headers. You can't use the 2 together according to everything I've read and tried.

**Comment by richp582** [comment]
Yea, that's always been the fear too

**Comment by DamienDoumer** [comment]
I still experience this same issue on Android.
