### ISSUE TITLE
[Bug] [WPF] NullReferenceException thrown when playing an HTTPS video link

### ISSUE THREAD

**Issue by Nessitro** [martijn00/XamarinMediaManager#609]
## 🐛 Bug Report

playing an HTTPS video link throws a System.NullReferenceException

### Expected behavior
HTTPS video link playing without crash
### Reproduction steps
1. add MediaManager forms nuget to the solution
2. call MediaManager.CrossMediaManager.Current.Init(); Forms.Init(); ... in MainWindow.xaml.cs
3. add videoView xaml with Source and AutoPlay=True or from code like this one:
https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4
4. app throws:

*Object reference not set to an instance of an object.*

#### **System.NullReferenceException** Source: PresentationCore

   HResult=0x80004003
   at System.Windows.Media.MediaPlayerState.OpenMedia(Uri source)
   at System.Windows.Media.MediaPlayerState.SetSource(Uri source)
   at System.Windows.Media.MediaPlayerState.Open(Uri source)
   at System.Windows.Controls.AVElementHelper.HandleStateChange()
   at System.Windows.Controls.AVElementHelper.OnLoaded(Object sender, RoutedEventArgs args)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

### Configuration
* Visual Studio 2019 **16.2.4**
* Xamarin.Forms **4.2.0.709249**
* Xamarin.Forms.Platform.WPF **4.2.0.709249**
* Plugin.MediaManager.Forms **0.8.8**

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This is a known issue in WPF: https://github.com/dotnet/wpf/issues/722

**Comment by lindexi** [comment]
@Nessitro @martijn00  Can this issue close? It be fixed on .NET Core in 2019, see https://github.com/dotnet/wpf/issues/722#issuecomment-506150037

**Comment by Nessitro** [comment]
@lindexi Thanks!
